name: "Test workflow"
on: issue_comment
jobs:
  test-job:
    name: "Test job"
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Comment on PR ${{ github.event.issue.number }}"
